# Auto-generated by CI — do not edit manually.
# Regenerated on each semantic release from Mearman/cascade.

class CascadeRelay < Formula
  desc "Opaque byte-pipe relay server for Cascade peers behind NATs"
  homepage "https://github.com/Mearman/cascade"
  version "0.1.76"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.76/cascade-relay-aarch64-macos.tar.gz"
      sha256 "0eff84a42093188b009f2e92f4a7b467ea676fbed77718e882337a31ff684d33"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.76/cascade-relay-x86_64-macos.tar.gz"
      sha256 "777a148465c56ce93c292e6d0e155e036ac90aeab71ac924450bb796dc3fec4c"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.76/cascade-relay-aarch64-linux.tar.gz"
      sha256 "3cdd908daff1965f9e3fbdfbd615ee585ccbbac6bf24fd44581444d724c30142"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.76/cascade-relay-x86_64-linux.tar.gz"
      sha256 "8f2bfe4a1dedfdf1d7d8e5008ca1e6c57cb8fde9f5adbc2eed5d09572ff42fdd"
    end
  end

  def install
    bin.install "cascade-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cascade-relay --version")
  end
end
