# Auto-generated by CI — do not edit manually.
# Regenerated on each semantic release from Mearman/cascade.

class Cascade < Formula
  desc "Cross-platform cloud storage filesystem client"
  homepage "https://github.com/Mearman/cascade"
  version "0.1.24"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.24/cascade-aarch64-macos.tar.gz"
      sha256 "0df3dbd1810244035fa4b2fe050ab55592caa2c7a5f132d654afd1f1464877fd"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.24/cascade-x86_64-macos.tar.gz"
      sha256 "120ca11231b67f397a63c3ab16a15bf91f75d58d2bbac99c668f7a95541d3553"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.24/cascade-aarch64-linux.tar.gz"
      sha256 "3bcdc0e826a57030c8724d0cd21a475db4218ea665b8225feb8cebcf6af8b5bd"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.24/cascade-x86_64-linux.tar.gz"
      sha256 "0e90952f6fb9e3981ea3d9c68269e586cce95be3da675fd09c62c1f583308860"
    end
  end

  def install
    bin.install "cascade"
  end

  test do
    assert_match version.to_s, shell_output("\#{bin}/cascade --version")
  end
end
