# Auto-generated by CI — do not edit manually.
# Regenerated on each semantic release from Mearman/cascade.

class CascadeRelay < Formula
  desc "Opaque byte-pipe relay server for Cascade peers behind NATs"
  homepage "https://github.com/Mearman/cascade"
  version "0.1.134"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.134/cascade-relay-aarch64-macos.tar.gz"
      sha256 "1fbf989b6b38aa2c2988c35c728670b03dc9cecd91d57bcc67b28fe62bbe5860"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.134/cascade-relay-x86_64-macos.tar.gz"
      sha256 "e701a9564af0e560a880575c3095ae5b188305f2d7c3c9421448f53ed311ff65"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.134/cascade-relay-aarch64-linux.tar.gz"
      sha256 "7269ec0d58a06fec4e8de52377d3590c7e504c1ac1be08ecded655ad3df1d447"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.134/cascade-relay-x86_64-linux.tar.gz"
      sha256 "171054a98e849dad98472f43265387e8cceda0b12f4e393d13ae29cbcb0c9bf3"
    end
  end

  def install
    bin.install "cascade-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cascade-relay --version")
  end
end
