# Auto-generated by CI — do not edit manually.
# Regenerated on each semantic release from Mearman/cascade.

class CascadeRelay < Formula
  desc "Opaque byte-pipe relay server for Cascade peers behind NATs"
  homepage "https://github.com/Mearman/cascade"
  version "0.1.66"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.66/cascade-relay-aarch64-macos.tar.gz"
      sha256 "9dab270062f3b5d08c5d621e17c8856d4fcf3108e6b10df1dfeafb06cb7c82b7"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.66/cascade-relay-x86_64-macos.tar.gz"
      sha256 "8857565a8d66148cda09a4c7a039b0b73b13597438163b3d9aacdbfbc0e23507"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.66/cascade-relay-aarch64-linux.tar.gz"
      sha256 "278bb41f75097f6ae3604c547865cc2b6e79aae6e7bc8b322ebcbb5681a80e9b"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.66/cascade-relay-x86_64-linux.tar.gz"
      sha256 "0731eed3b0cc4922b19f2c7bfa39c937470fbadb078ce3d4759a7f073d64d5fa"
    end
  end

  def install
    bin.install "cascade-relay"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cascade-relay --version")
  end
end
