# Auto-generated by CI — do not edit manually.
# Regenerated on each semantic release from Mearman/cascade.

class Cascade < Formula
  desc "Cross-platform cloud storage filesystem client"
  homepage "https://github.com/Mearman/cascade"
  version "0.1.131"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.131/cascade-aarch64-macos.tar.gz"
      sha256 "ed3978c5201703b066972380e1ebf7de6e1b9e4399a27add36fae7992ba64706"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.131/cascade-x86_64-macos.tar.gz"
      sha256 "125b880d51cb97356b2e8819d04e2736334467fc8a98dca98ca18c54e957fd81"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.131/cascade-aarch64-linux.tar.gz"
      sha256 "cfac3e09f3837cba7426ff96641210c0d8725a28e439e5ec3e393cf68eb2c174"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.131/cascade-x86_64-linux.tar.gz"
      sha256 "075a8b1afec9779ee683cf79d4ef6616aa0a6d38729a9c5bf7a52159393521db"
    end
  end

  def install
    bin.install "cascade"
  end

  service do
    run [opt_bin/"cascade", "start"]
    keep_alive true
    log_path var/"log/cascade.log"
    error_log_path var/"log/cascade.err.log"
  end

  test do
    assert_match version.to_s, shell_output("\#{bin}/cascade --version")
  end
end
