# Auto-generated by CI — do not edit manually.
# Regenerated on each semantic release from Mearman/cascade.

class Cascade < Formula
  desc "Cross-platform cloud storage filesystem client"
  homepage "https://github.com/Mearman/cascade"
  version "0.1.52"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.52/cascade-aarch64-macos.tar.gz"
      sha256 "793bafa65948abb4ce092405d6a6f57c8c974a39f86a9344955df8e6eaa2860f"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.52/cascade-x86_64-macos.tar.gz"
      sha256 "bd93ef716081823865b171b789607336124df5c8114e3bc317bf5db8e22b711b"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.52/cascade-aarch64-linux.tar.gz"
      sha256 "320afbdf17bb30329e299dede5040323bba73c1d9dbd2ee0d63a5fb753304b53"
    else
      url "https://github.com/Mearman/cascade/releases/download/cascade-v0.1.52/cascade-x86_64-linux.tar.gz"
      sha256 "6727070fccf315f13b854d0f58acfbc56715121ffd98ebace5911df9524452a6"
    end
  end

  def install
    bin.install "cascade"
  end

  test do
    assert_match version.to_s, shell_output("\#{bin}/cascade --version")
  end
end
